name: 'tests'

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  build:
    runs-on: windows-latest

    defaults:
      run:
        shell: cmd

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Setup Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Setup PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install -U platformio

    - name: Build Firmware
      run: platformio run --project-dir .\Embedded\Maxmix -e nano-cli

    - name: Setup NuGet.exe
      uses: NuGet/setup-nuget@v1.0.5
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1
    - name: Setup MSBuild ExtensionPack
      run: choco install msbuild.extensionpack --version=4.0.15.0 -y
     
    - name: Restore Application packages
      run: nuget restore Desktop\Application\MaxMix.sln
    - name: Build Application
      run: msbuild Desktop\Build.msbuild -p:SolutionDir=Application -p:Version=0.0.0.0 -p:Configuration=Debug -p:Platform="Any CPU"

    - name: Restore DriverInstaller packages
      run: nuget restore Desktop\DriverInstaller\DriverInstaller.sln
    - name: Build DriverInstaller
      run: msbuild Desktop\Build.msbuild -p:SolutionDir=DriverInstaller -p:Version=0.0.0.0 -p:Configuration=Debug -p:Platform="Any CPU"

    - name: Restore FirmwareInstaller packages
      run: nuget restore Desktop\FirmwareInstaller\FirmwareInstaller.sln
    - name: Build FirmwareInstaller
      run: msbuild Desktop\Build.msbuild -p:SolutionDir=FirmwareInstaller -p:Version=0.0.0.0 -p:Configuration=Debug -p:Platform="Any CPU"
    
